version: "2"

services:
  redis:
    image: redis:5.0
    container_name: "gokurou-dev-redis"
    ports:
      - "11111:6379"
  mysql:
    image: mysql:5.7
    container_name: "gokurou-dev-mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=gokurou_test"
      - "MYSQL_ROOT_PASSWORD=test1234"