version: "2"

services:
  redis:
    image: redis:5.0
    container_name: "gokurou-redis"
    ports:
      - "11111:6379"
  mysql:
    image: mysql:5.7
    container_name: "gokurou-mysql"
    volumes:
      - "./docker/mysql:/docker-entrypoint-initdb.d"
    ports:
      - "11112:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=gokurou1234"
  s3:
    image: minio/minio
    container_name: "gokurou-s3"
    command: server /data
    ports:
      - "11113:9000"
    environment:
        - "MINIO_ACCESS_KEY=gokurou-s3-access-key"
        - "MINIO_SECRET_KEY=gokurou-s3-secret-key"