CREATE TABLE IF NOT EXISTS urls (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gwn INTEGER NOT NULL,
    tab_joined_url MEDIUMTEXT CHARACTER SET ascii NOT NULL,

    INDEX gwn_index(gwn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;