#!/bin/bash
# need brew install FiloSottile/musl-cross/musl-cross
GOOS=linux \
GOARCH=amd64 \
CGO_ENABLED=1 \
CC=/usr/local/bin/x86_64-linux-musl-cc \
    go build --ldflags '-linkmode external -extldflags "-static"' -a -o $1 cmd/gokurou/gokurou.go