
CREATE DATABASE IF NOT EXISTS gokurou_dev CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS gokurou_dev.urls (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gwn INTEGER NOT NULL,
    tab_joined_url MEDIUMTEXT CHARACTER SET ascii NOT NULL,
    INDEX gwn_index(gwn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE DATABASE IF NOT EXISTS gokurou_test CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS gokurou_test.urls (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gwn INTEGER NOT NULL,
    tab_joined_url MEDIUMTEXT CHARACTER SET ascii NOT NULL,
    INDEX gwn_index(gwn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
